### ISSUE TITLE
Backlight (KB)

### ISSUE THREAD

**Issue by Pretuer** [EtienneMueller/razer-blade-data-science#1]
Hi, I have the Blade-15-Base-Model-Late-2020:was wondering if you could help creae a PR or custom version of open-razer, any iformation needed about the laptop? thanks, Derek

**Comment by EtienneMueller** [comment]
Sorry, I tried to add support for the 2021 base model (https://github.com/openrazer/openrazer/issues/1442) but it didn't for the other users. Without having the notebook myself I can't troubleshoot anything. Best, Etienne

**Comment by Pretuer** [comment]
OKay no problem could you at lease send the pulse effects config file for the Blade?

**Comment by EtienneMueller** [comment]
> OKay no problem could you at lease send the pulse effects config file for the Blade?

Oh sorry, I somehow thought I already added it to the repository. I now did!
